version: "3.2"
services:
  php:
    build: './dev-scripts/'
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
      - ./src/:/var/www/src/
      - ./vendor/:/var/www/vendor/
    environment:
      - DATABASE_USER=root
      - DATABASE_PASS=dev_pass
      - DATABASE_DSN=mysql:host=mysql;dbname=dev_db
  nginx:
    build: './nginx/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html
  mysql:
    image: mysql:8.0.20
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=dev_pass
      - MYSQL_DATABASE=dev_db
networks:
  frontend:
  backend: