FROM php:7.4-fpm-alpine3.11
RUN apk update; \
    apk upgrade; \
    apk add build-base autoconf; \
    pecl install xdebug;
COPY php.ini /usr/local/etc/php/php.ini
RUN docker-php-ext-install pdo_mysql
RUN mkdir /var/www/twig
RUN chown -R www-data:www-data /var/www/twig